nome = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(nome)))
print('Só tem espaços? {}'.format(nome.isspace()))
print('É um numero? {}'.format(nome.isnumeric()))
print('É alfabetico? {}'.format(nome.isalpha()))
print('É alfanumerico? {}'.format(nome.isalnum()))
print('Está em maisculas? {}'.format(nome.isupper()))
print('Está em minusculas? {}'.format(nome.islower()))
print('Está capitalizada? {}'.format(nome.istitle()))